### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LuShuYangMing** [GSEA-MSigDB/GSEA_R#4]
1: In tag.indicator * correl.vector :
  longer object length is not a multiple of shorter object length

**Comment by ACastanza** [comment]
Hello,

Both the tag.indicator and correl.vector are generated directly from your dataset. It's impossible to determine what the specific cause of the error is here without more information. However, some possibilities are that the CLS file is not properly formatted resulting in a mismatch between the number of samples/phenotypes defined in the cls (correl.vector), or there could be missing data for some of the genes (tag.indicators) in the input GCT file (although this shouldn't happen). Or it could be any of several less likely things.

If you're willing to confidentially send the input data you used for this analysis to gsea-team@broadinstitute.org I can investigate this error further. Your data will not be used for anything other than debugging, and will remain confidential and not be shared.

-Anthony

Anthony S. Castanza, PhD
Curator, Molecular Signatures Database
Mesirov Lab, Department of Medicine
University of California, San Diego
